#!/usr/bin/env python3

import sys
from datetime import datetime as dt
import socket

if len(sys.argv) == 2:
  target = socket.gethostbyname(sys.argv[1]) # Traduce host a IPV4
else:
  print("Argumentos invalidos")
  print("Syntax: python3 port_scanner.py [ip/hostname]")

print("Escanenado Objetivo: " + target)
print("Tiempo transcurrido: " + str(dt.now()))
print('-' * 50)

try:
  for port in range(1,65535):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    socket.setdefaulttimeout(0.5)
    result = s.connect_ex((target, port))
    if result == 0:
      print("Puerto {} esta abierto".format(port))
    s.close 
except KeyboardInterrupt:
  print('\nSaliendo...')
  sys.exit()
except socket.gaierror:
  print("No se puede resolver nombre de Host")
  sys.exit()
except socket.error:
  print("No se pudo conectar al servidor")
  sys.exit()
